Домашнее задание по лекциям React/Redux
novvember/hh-reviewer-finder pull request #1
Opened 2023-01-29 18:51 UTC by novvember

## Деплой на GH Pages:
[`novvember.github.io/hh-reviewer-finder`](https://novvember.github.io/hh-reviewer-finder)

## Комментарий
Сделал на Redux Toolkit, так как и сам Redux очень настоятельно рекомендует его использовать, и хотелось побольше изучить его, и хотелось использовать состяния танков во время выполнения и мемоизированные селекторы.

## Сделано
- приложение создано на базе Create React App
- Typescript без использования типа any
- в качестве визуальной части использовал компоненты Ant Design, но старался использовать меньше их логики, чтобы больше писать вручную (например, не использовал готовые компоненты форм)
- глобальный стейт хранится в Redux, локальный (например, значения инпутов в форме по мере ввода) -- в самих компонентах
- глобальный стейт при изменении сохраняется в local storage, при загрузке страницы начальное значение стейта берется из local storage (при наличии)
- сам стейт создан с использованием Redux Toolkit, асинхронные запросы данных выполняются через createAsyncThunk, некоторые селекторы дополнительно замемоизированы через createSelector
- по возможности все данные компонентами берутся из стейта, почти нет пропсов
- запрос на сервер выполняется в момент сохранения данных формы (чтобы получить список потенциальных ревьюеров до нажатия главной кнопки поиска ревьюера)
- есть состояния загрузки, ошибок и успешного выполнения у всех кнопок
- доработал запрос контрибьюторов репозитория для больших репозиториев (выполняется последовательно несколько постраничных запросов)

## Что можно улучшить в дальнешем
- вынести некоторые константы в отдельный файл с конфигурацией (например, параметры смены пользователей при поиске ревьюера)
- выделить в отдельные компоненты некоторые части, чтобы упростить чтение приложения
- продумать вместе с заказчиком логику переключения состояний приложения: например, когда должны отображаться те или иные элементы, должны ли пропадать результаты предыдущего поиска ревьюера при вводе новый данных или нет. Сейчас эти моменты неясны, так что делал на свой вкус.
- убрать кнопку сохранения данных, тогда запрос и само сохранение можно делать по клику на общую кнопку либо при фокусе на поле с черным списком, но тут опять же неясна общая логика, необходимо прояснение.

2023-01-30 08:35 UTC, AndreyGladkov requested changes
Спасибо за решение, в целом все хорошо, молодец! Момент касательно реакта я подсветил связанный с избыточной|недостаточной мемоизацией (в зависимости от твоей задумки). Остальные комментарии больше по логике приложения.

2023-01-30 08:35 UTC, AndreyGladkov commented on src/components/Result.tsx
> +      return getRandomLogin();
можно отфильтровать contributors по blacklist, и потом на нем вызывать рандом. Дабы избегать рекурсии. 
В твоем случае можно получить баг, бесконечная рекурсия, если в blacklist списке будут все из  списка contributors.

2023-01-30 08:35 UTC, AndreyGladkov commented on src/components/Result.tsx
> +  async function handleClick() {
async в данном случае не несет смысла, раз ты не авейтиш ни его, не внутри какой либо код.

2023-01-30 08:35 UTC, AndreyGladkov commented on src/components/Result.tsx
> +    setTimeout(() => setIsLoading(false), 5000);
магические констаны обычно выносим в именованные типо таймаут выбора ревьюера.

2023-01-30 08:35 UTC, AndreyGladkov commented on src/components/Settings.tsx
> +  const contributorsOptions = useMemo(
в данном случае мемоизация не имеет никакого смысла, ты устанавливаешь компоненту Select следующие props:
```
onChange={handleListChange}
options={contributorsOptions}
```
handleListChange - при каждом ререндере будет формировать новую ссылку, и компонент селект будет обновляться всегда даже если contributors не изменился, если хотелось оптимизаций, то надо его унести в useCallback.

2023-01-30 08:35 UTC, AndreyGladkov commented on src/api/getContributors.ts
> +    if (!res || res.length === 0) break;
кажется тут можно проверять что `res.length < per_page` и не делать лишний запрос за пустой страницей.

2023-01-30 19:18 UTC, novvember commented on src/components/Result.tsx
> +      return getRandomLogin();
Переделал функцию. Плюс добавил фильтр через множество, чтобы несколько раз не проходить по одному из списку. Плюс мемоизировал результат получения массива подходящих пользователей, чтобы не выполнять перебор при каждом перерендере.

2023-01-30 19:18 UTC, novvember commented on src/components/Result.tsx
> +  async function handleClick() {
Да, действительно не нужно, осталось от предыдущих вариантов, когда думал сделать это через промисы.

2023-01-30 19:29 UTC, novvember commented on src/components/Result.tsx
> +    setTimeout(() => setIsLoading(false), 5000);
Вынес все встречаемые константы в отдельный файл

2023-01-30 19:33 UTC, novvember commented on src/components/Settings.tsx
> +  const contributorsOptions = useMemo(
Добавил handleListChange  в useCallback

2023-01-31 06:32 UTC, AndreyGladkov approved these changes

2023-01-31 21:48 UTC, merged